chore: add checks for empty vars

diff --git a/bin/rename_phoenix_project b/bin/rename_phoenix_project
--- a/bin/rename_phoenix_project
+++ b/bin/rename_phoenix_project
@@ -2,12 +2,27 @@
 
 set -e
 
-CURRENT_NAME="PhoenixStarter"
-CURRENT_OTP="phoenix_starter"
+for ARGUMENT in "$@"
+do
+   KEY=$(echo $ARGUMENT | cut -f1 -d=)
 
-NEW_NAME="NewName"
-NEW_OTP="new_name"
+   KEY_LENGTH=${#KEY}
+   VALUE="${ARGUMENT:$KEY_LENGTH+1}"
 
+   export "$KEY"="$VALUE"
+done
+
+check_empty_variable() {
+  if [ -z "$1" ]; then
+    echo "Error: variable $2 is empty" >&2
+    exit 1
+  fi
+}
+
+check_empty_variable "$CURRENT_NAME" "CURRENT_NAME"
+check_empty_variable "$CURRENT_OTP" "CURRENT_OTP"
+check_empty_variable "$NEW_NAME" "NEW_NAME"
+check_empty_variable "$NEW_OTP" "NEW_OTP"
 
 
 if [[ "$OSTYPE" == "darwin"* ]]; then
